### PR TITLE
Token endpoint auth method fix and logout fix

### LINKED ISSUE #128: token_endpoint_auth_method probably shouldn't be unset like this
https://github.com/likeandscribe/unravel/blob/19dc7fd6196377be2d4a03494d4b00dab19d4a79/packages/frontpage/lib/auth.ts#L75

### PR DESCRIPTION
**Pull request by tom-sherman**
This also changes the behaviour of login for some reason: you no longer need to accept the permissions every time you login.

Closes #128

### CODE REVIEW

File: packages/frontpage/app/(app)/layout.tsx [hunk 1]
```diff
@@ -133,7 +133,6 @@ async function LoginOrLogout() {
               await signOut();
               deleteAuthCookie(cookies());
               revalidatePath("/", "layout");
-              redirect("/");
```
Comment (tom-sherman) [inline packages/frontpage/app/(app)/layout.tsx:136]: Removed this because there's a bug in next.js that doesn't revalidate layouts when combined with a redirect.

https://github.com/vercel/next.js/issues/70483

**Review by WillCorrigan — APPROVED** [review]
